# Question 1:

Try to create the backpropagation and feedforward in python by creating function.

In [1]:
import numpy as np

# Considering sample data as follows
# X = (hours working, hours sleeping), y = score on test
x = np.array(([8, 7], [9, 6], [4, 6], [9, 8]), dtype=float)  # input data
y = np.array(([92], [86], [89]), dtype=float)  # output

# scale units
x = x / np.amax(x, axis=0)  # scaling input data
y = y / 100  # scaling output data (max test score is 100)

# split data
X = np.split(x, [3])[0]  # training data
xPredicted = np.split(x, [3])[1]  # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.88888889 0.875     ]
 [1.         0.75      ]
 [0.44444444 0.75      ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.62918882]
 [0.63422848]
 [0.64633018]]
Loss: 
0.06497296791543773


# 1

Input (scaled): 
[[0.88888889 0.875     ]
 [1.         0.75      ]
 [0.44444444 0.75      ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.64614351]
 [0.65152585]
 [0.66272726]]
Loss: 
0.056703915305127056


# 2

Input (scaled): 
[[0.88888889 0.875     ]
 [1.         0.75      ]
 [0.44444444 0.75      ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.66267727]
 [0.66833647]
 [0.6783357 ]]
Loss: 
0.04925055710896383


# 3

Input (scaled): 
[[0.88888889 0.875     ]
 [1.         0.75      ]
 [0.44444444 0.75      ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.67863056]
 [0.68450163]
 [0.69307853]]
Loss: 
0.04261231566844659


# 4

Input (scaled): 
[[0.88888889 0.875     ]
 [1.         0.75      ]
 [0.444